# Code alongs merging

## Setup

In [2]:
import pandas as pd
import numpy as np

# a range
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
# every column and row a panda series
df1 = pd.DataFrame(np.arange(16).reshape(4,4), columns = list("ABCD"))
df1

A   B   C   D
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [6]:
df2 = pd.DataFrame(np.zeros((3,4)), columns = list("ABCD"))
df2

A    B    C    D
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0

In [7]:
df3 = pd.DataFrame(np.ones((4,3)), index = [1,5,10,15])
df3

0    1    2
1   1.0  1.0  1.0
5   1.0  1.0  1.0
10  1.0  1.0  1.0
15  1.0  1.0  1.0

## Concat

- Use when wanting to combine vertically (axis = 0) (append rows, aligns intersecting columns)
- Can also be used to merge along columns (axis = 0), but aligns only on the index and not columns of choice (like merge())

In [42]:
df1, df2

(    A   B   C   D
 0   0   1   2   3
 1   4   5   6   7
 2   8   9  10  11
 3  12  13  14  15,
      A    B    C    D
 0  0.0  0.0  0.0  0.0
 1  0.0  0.0  0.0  0.0
 2  0.0  0.0  0.0  0.0)

In [43]:
pd.concat([df1, df2])

# axis = 0 is default ("rows")
# ALONG which axis to merge

# when joining along rows, intersecting columns are aligned
# default is join = "outer" so cols from both dfs

A     B     C     D
0   0.0   1.0   2.0   3.0
1   4.0   5.0   6.0   7.0
2   8.0   9.0  10.0  11.0
3  12.0  13.0  14.0  15.0
0   0.0   0.0   0.0   0.0
1   0.0   0.0   0.0   0.0
2   0.0   0.0   0.0   0.0

In [44]:
# merge ALONG axis 1, aligning index
# index 3 only exists in df1 so filled with NaN in df2 since join = "outer"
pd.concat([df1, df2], axis=1)

A   B   C   D    A    B    C    D
0   0   1   2   3  0.0  0.0  0.0  0.0
1   4   5   6   7  0.0  0.0  0.0  0.0
2   8   9  10  11  0.0  0.0  0.0  0.0
3  12  13  14  15  NaN  NaN  NaN  NaN

In [45]:
df1, df3

(    A   B   C   D
 0   0   1   2   3
 1   4   5   6   7
 2   8   9  10  11
 3  12  13  14  15,
       0    1    2
 1   1.0  1.0  1.0
 5   1.0  1.0  1.0
 10  1.0  1.0  1.0
 15  1.0  1.0  1.0)

In [46]:
# adds ROWS
# adds df1 rows first, then adds df3 rows
pd.concat([df1, df3])

A     B     C     D    0    1    2
0    0.0   1.0   2.0   3.0  NaN  NaN  NaN
1    4.0   5.0   6.0   7.0  NaN  NaN  NaN
2    8.0   9.0  10.0  11.0  NaN  NaN  NaN
3   12.0  13.0  14.0  15.0  NaN  NaN  NaN
1    NaN   NaN   NaN   NaN  1.0  1.0  1.0
5    NaN   NaN   NaN   NaN  1.0  1.0  1.0
10   NaN   NaN   NaN   NaN  1.0  1.0  1.0
15   NaN   NaN   NaN   NaN  1.0  1.0  1.0

In [47]:
# when merging along columns, intersecting indices are aligned
pd.concat([df1, df3], axis = 1)

# if wanting to align along a column instead of index, use merge()
# if wanting to align along all indices of one df, and only intersection of the other
# use join() or merge() with left_index = True

A     B     C     D    0    1    2
0    0.0   1.0   2.0   3.0  NaN  NaN  NaN
1    4.0   5.0   6.0   7.0  1.0  1.0  1.0
2    8.0   9.0  10.0  11.0  NaN  NaN  NaN
3   12.0  13.0  14.0  15.0  NaN  NaN  NaN
5    NaN   NaN   NaN   NaN  1.0  1.0  1.0
10   NaN   NaN   NaN   NaN  1.0  1.0  1.0
15   NaN   NaN   NaN   NaN  1.0  1.0  1.0

In [48]:
# inner only gives the intersecting index
pd.concat([df1, df3], axis = 1, join = "inner")

A  B  C  D    0    1    2
1  4  5  6  7  1.0  1.0  1.0

In [49]:
# indexes added, but since no columns are intersecting they are empty
pd.concat([df1, df3], axis = 0, join = "inner")

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 1, 5, 10, 15]

## Merge

Use this over concat when combining complementary columns from two different DataFrames where you want to match on a column like "ID", since concat aligns only on index when combining columns (axis = 1)

- used to combine dataframes on values of common columns (on="key"), defaults to intersecting columns
- indices can also be used (left_index = True and/or right_index=True)

In [8]:
left = pd.DataFrame(
    {
        "key": ["K0", "K0", "K1", "K2"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"]
    }
)

right = pd.DataFrame(
    {
        "key": ["K0", "K1", "K2", "K3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"]
    }
)

left, right

(  key   A   B
 0  K0  A0  B0
 1  K0  A1  B1
 2  K1  A2  B2
 3  K2  A3  B3,
   key   C   D
 0  K0  C0  D0
 1  K1  C1  D1
 2  K2  C2  D2
 3  K3  C3  D3)

In [18]:
# defaults
pd.merge(
    left,
    right,
    how="inner", # outer retains rows that only exist in one df
    on=None, # column to join on (default: intersection of columns)
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    sort=True,
    suffixes=("_x", "_y"),
    copy=True,
    indicator=False,
    validate=None,
)

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K0  A1  B1  C0  D0
2  K1  A2  B2  C1  D1
3  K2  A3  B3  C2  D2

In [28]:
# default on is intersection of columns which is "key" here, so same output as above
pd.merge(left, right, on = "key", indicator=True)

# simlar to concat's merging on axis = 1 but merges rows using "key" instead of index

key   A   B   C   D _merge
0  K0  A0  B0  C0  D0   both
1  K0  A1  B1  C0  D0   both
2  K1  A2  B2  C1  D1   both
3  K2  A3  B3  C2  D2   both

In [29]:
# syntax with method (equivalent to above)
left.merge(right, on = "key", indicator=True)

key   A   B   C   D _merge
0  K0  A0  B0  C0  D0   both
1  K0  A1  B1  C0  D0   both
2  K1  A2  B2  C1  D1   both
3  K2  A3  B3  C2  D2   both

In [30]:
left.merge(right, on = "key", how = "outer", indicator=True)

key    A    B   C   D      _merge
0  K0   A0   B0  C0  D0        both
1  K0   A1   B1  C0  D0        both
2  K1   A2   B2  C1  D1        both
3  K2   A3   B3  C2  D2        both
4  K3  NaN  NaN  C3  D3  right_only

In [31]:
left = pd.DataFrame(
    {
        "key1": ["K0", "K0", "K1", "K2"],
        "key2": ["K0", "K1", "K0", "K1"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)

right = pd.DataFrame(
    {
        "key1": ["K0", "K1", "K1", "K2"],
        "key2": ["K0", "K0", "K0", "K0"],
        "A": ["A0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    }
)

left, right

(  key1 key2   A   B
 0   K0   K0  A0  B0
 1   K0   K1  A1  B1
 2   K1   K0  A2  B2
 3   K2   K1  A3  B3,
   key1 key2   A   D
 0   K0   K0  A0  D0
 1   K1   K0  C1  D1
 2   K1   K0  C2  D2
 3   K2   K0  C3  D3)

In [38]:
# if there are multiple rows with same value in aligning column, they are all included
# if those rows differ in other columns, those columns get duplicated 

pd.merge(left, right, on = "key1", indicator=True)

key1 key2_x A_x   B key2_y A_y   D _merge
0   K0     K0  A0  B0     K0  A0  D0   both
1   K0     K1  A1  B1     K0  A0  D0   both
2   K1     K0  A2  B2     K0  C1  D1   both
3   K1     K0  A2  B2     K0  C2  D2   both
4   K2     K1  A3  B3     K0  C3  D3   both

In [39]:
# rows reflecting all combinations of differing columns are added
# cartesian product!
pd.merge(left, right, on = "key2", indicator=True)

key1_x key2 A_x   B key1_y A_y   D _merge
0     K0   K0  A0  B0     K0  A0  D0   both
1     K0   K0  A0  B0     K1  C1  D1   both
2     K0   K0  A0  B0     K1  C2  D2   both
3     K0   K0  A0  B0     K2  C3  D3   both
4     K1   K0  A2  B2     K0  A0  D0   both
5     K1   K0  A2  B2     K1  C1  D1   both
6     K1   K0  A2  B2     K1  C2  D2   both
7     K1   K0  A2  B2     K2  C3  D3   both

In [50]:
left, right

(  key1 key2   A   B
 0   K0   K0  A0  B0
 1   K0   K1  A1  B1
 2   K1   K0  A2  B2
 3   K2   K1  A3  B3,
   key1 key2   A   D
 0   K0   K0  A0  D0
 1   K1   K0  C1  D1
 2   K1   K0  C2  D2
 3   K2   K0  C3  D3)

In [41]:
left.merge(right, on = ["key1", "key2"], indicator=True)

key1 key2 A_x   B A_y   D _merge
0   K0   K0  A0  B0  A0  D0   both
1   K1   K0  A2  B2  C1  D1   both
2   K1   K0  A2  B2  C2  D2   both

In [43]:
# how = "right" uses keys from right frame only
left.merge(right, on = ["key1", "key2"], indicator=True, how = "right", suffixes=["_left", "_right"])

key1 key2 A_left    B A_right   D      _merge
0   K0   K0     A0   B0      A0  D0        both
1   K1   K0     A2   B2      C1  D1        both
2   K1   K0     A2   B2      C2  D2        both
3   K2   K0    NaN  NaN      C3  D3  right_only

## Join

- combines columns based on index of first df
- uses merge() with the option left_index=True

In [52]:
left = pd.DataFrame(
    {"A": ["A0", "A1", "A2"], "B": ["B0", "B1", "B2"]}, index=["K0", "K1", "K2"]
)

right = pd.DataFrame(
    {"C": ["C0", "C2", "C3"], "D": ["D0", "D2", "D3"]}, index=["K0", "K2", "K3"]
)

left, right

(     A   B
 K0  A0  B0
 K1  A1  B1
 K2  A2  B2,
      C   D
 K0  C0  D0
 K2  C2  D2
 K3  C3  D3)

In [53]:
# note we join on K1 which only exists in left -> so default is a left join
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [54]:
# indices from right -> right join
right.join(left)
left.join(right, how = "right")

A    B   C   D
K0   A0   B0  C0  D0
K2   A2   B2  C2  D2
K3  NaN  NaN  C3  D3

--- 
## Webscraping HTML tables

In [61]:
fifa_tables = pd.read_html("https://en.wikipedia.org/wiki/FIFA")

len(fifa_tables), type(fifa_tables)

(31, list)

In [62]:
fifa_tables[0].head()

0  \
0  Fédération internationale de Football Associat...   
1                                               Logo   
2  Map of the members of FIFA according to their ...   
3                                       Abbreviation   
4                                            Founded   

                                                   1  
0  Fédération internationale de Football Associat...  
1                                               Logo  
2  Map of the members of FIFA according to their ...  
3                                            FIFA[1]  
4                         21 May 1904; 118 years ago

In [63]:
fifa_tables[2].head()

No.                               Name         Country      Took office  \
0   1                      Robert Guérin          France      23 May 1904   
1   2             Daniel Burley Woolfall  United Kingdom      4 June 1906   
2   —  Cornelis August Wilhelm Hirschman     Netherlands  24 October 1918   
3   3                        Jules Rimet          France     1 March 1921   
4   4               Rodolphe Seeldrayers         Belgium     21 June 1954   

       Left office            Note  
0      4 June 1906             NaN  
1  24 October 1918  Died in office  
2             1920          Acting  
3     21 June 1954             NaN  
4   7 October 1955  Died in office

In [64]:
title_holders = pd.read_html("https://en.wikipedia.org/wiki/FIFA", match = "Runners-up")

# tables that match is added to a list. in this case, only one match
len(title_holders)

1

In [65]:
# match can be string or regexp (default ".+" anything one or more)
title_holders = pd.read_html("https://en.wikipedia.org/wiki/FIFA", match = "Runners-up", header=0)[0]

# try out skiprows

title_holders.head()

Competition      Unnamed: 1            Year  \
0                            National teams  National teams  National teams   
1                            FIFA World Cup             NaN    2018 (Final)   
2  Men's Olympic Football Tournament (U-23)             NaN    2020 (Final)   
3                       FIFA U-20 World Cup             NaN    2019 (Final)   
4                       FIFA U-17 World Cup             NaN    2019 (Final)   

        Champions           Title      Runners-up      Unnamed: 6  \
0  National teams  National teams  National teams  National teams   
1          France             2nd         Croatia             NaN   
2          Brazil             2nd           Spain             NaN   
3         Ukraine             1st     South Korea             NaN   
4          Brazil             4th          Mexico             NaN   

  Next edition[55]  
0   National teams  
1     2022 (Final)  
2     2024 (Final)  
3     2023 (Final)  
4     2023 (Final)